language: objective-c
osx_image: xcode9.3
xcode_project: ./wasmovie.xcodeproj
xcode_sdk: iphonesimulator10.1

before_install:
- rm -rf /Users/travis/Library/Developer/Xcode/DerivedData/wasmovie-*/
- rvm use $RVM_RUBY_VERSION

install:
- bundle
- bundle install --without=documentation --path ../travis_bundle_dir

script:
- xcodebuild -scheme wasmovie -destination "platform=iOS Simulator,name=iPhone 6s,OS=10.1" clean test | xcpretty

after_success: 
  - slather
  - bash <(curl -s https://codecov.io/bash) -f ./TestsReports/cobertura.xml