language: swift
osx_image: xcode9.3
xcode_project: WasMovie.xcodeproj
xcode_scheme: WasMovie
xcode_sdk: iphonesimulator9.0

branches:
  only:
  - master
  - wip/travis

before_install:
  - rm -rf /Users/travis/Library/Developer/Xcode/DerivedData/WasMovie-*/
  - rvm use $RVM_RUBY_VERSION
  - brew update
  - brew upgrade swiftlint
  - pod repo update

script:
- xcodebuild -workspace WasMovie.xcworkspace -scheme WasMovie -destination "platform=iOS Simulator,name=iPhone 6,OS=9.0" clean test | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash) -t ccaac61c-1ef8-4f55-808c-671c14ba2e52
